apiVersion: v2
appVersion: "1.0"
description: A Helm chart for ccd-test-stubs-service App
name: ccd-test-stubs-service
home: https://github.com/hmcts/ccd-test-stubs-service
version: 1.0.8
maintainers:
  - name: HMCTS CCD Dev Team
    email: ccd-devops@HMCTS.NET
dependencies:
  - name: java
    version: 2.17.0
    repository: '@hmctspublic'
